require 'plugins.ui.alpha'
require 'plugins.ui.bufferline'
require 'plugins.ui.comment-box'
require 'plugins.ui.gitsigns'
require 'plugins.ui.indentline'
require 'plugins.ui.lualine'
-- require 'plugins.ui.heirline'
require 'plugins.ui.navic'
