cp -r ~/.config/hypr .
cp -r ~/.config/kitty .
cp -r ~/.config/neofetch .
cp -r ~/.config/nvim .
cp -r ~/.config/rofi .
cp -r ~/.config/swappy .
cp -r ~/.config/swaylock .
cp -r ~/.config/swww .
cp -r ~/.config/waybar .
cp -r ~/.config/wlogout .
cp -r ~/.zshrc .
cp -r ~/.vimrc .
cp -r ~/.zimrc .
cp -r ~/.ideavimrc .
